// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDleZcJI1pYtsL496hGHJZzTxfPaWWZjOc',
    appId: '1:691353106685:web:17d901b5d1b5bb645b6694',
    messagingSenderId: '691353106685',
    projectId: 'nnnnn-85af4',
    authDomain: 'nnnnn-85af4.firebaseapp.com',
    storageBucket: 'nnnnn-85af4.firebasestorage.app',
    measurementId: 'G-X0FZPCZ9HB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSC2AjNg_yhLqUOGT2WMi9WnyQXEuu2Co',
    appId: '1:691353106685:android:6429eed28d59e1d65b6694',
    messagingSenderId: '691353106685',
    projectId: 'nnnnn-85af4',
    storageBucket: 'nnnnn-85af4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHwIS6Qw2SMAalDxA3CJ8B4hu7r6XkZ0U',
    appId: '1:691353106685:ios:693bb00d13c67e645b6694',
    messagingSenderId: '691353106685',
    projectId: 'nnnnn-85af4',
    storageBucket: 'nnnnn-85af4.firebasestorage.app',
    iosBundleId: 'com.example.foodiaChef',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHwIS6Qw2SMAalDxA3CJ8B4hu7r6XkZ0U',
    appId: '1:691353106685:ios:693bb00d13c67e645b6694',
    messagingSenderId: '691353106685',
    projectId: 'nnnnn-85af4',
    storageBucket: 'nnnnn-85af4.firebasestorage.app',
    iosBundleId: 'com.example.foodiaChef',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDleZcJI1pYtsL496hGHJZzTxfPaWWZjOc',
    appId: '1:691353106685:web:e77e7dccb72cf9ad5b6694',
    messagingSenderId: '691353106685',
    projectId: 'nnnnn-85af4',
    authDomain: 'nnnnn-85af4.firebaseapp.com',
    storageBucket: 'nnnnn-85af4.firebasestorage.app',
    measurementId: 'G-HYX7WT8JJ2',
  );
}
